ccflags-y += -Idrivers/media/platform/msm/camera_smartisan
ccflags-y += -Idrivers/media/platform/msm/camera_smartisan/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/camera_smartisan/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
